#!/bin/bash

set -e

PKG_VER="__PKG_VER__"
DATA_ROOT="${XDG_DATA_DIR:-${HOME}/.local/share}/thedarkmod"
DATA_SRC="/usr/share/thedarkmod"
PKG_META="${DATA_ROOT}/pkg_meta"
GAME_PATH="/usr/libexec/thedarkmod"

mkdir -p "${DATA_ROOT}"

try_update_links() {
  needs_update=1

  if [[ -f "${PKG_META}" ]]; then
    test "$(head -1 "${PKG_META}")" = "${PKG_VER}" && needs_update=0
  fi

  if [[ ${needs_update} -ne 0 ]]; then
    update_links
  fi
}

update_links() {
  # clean old links
  if [[ -f "${PKG_META}" ]]; then
    tail +2 "${PKG_META}" | xargs -ri rm -v "${DATA_ROOT}/{}"
  fi

  echo "${PKG_VER}" > "${PKG_META}_new"

  for file in $(find "${DATA_SRC}" -type f); do
    bn="$(realpath --relative-to "${DATA_SRC}" "${file}")"
    mkdir -p "${DATA_ROOT}/$(dirname "${bn}")"
    ln -sv "${file}" "${DATA_ROOT}/${bn}"
    echo "${bn}" >> "${PKG_META}_new"
  done

  mv "${PKG_META}_new" "${PKG_META}"
}

try_update_links

cd "${DATA_ROOT}"
"${GAME_PATH}" "${@}"
