# Copyright 2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

inherit npm2x

NPM_MODULES="
	xdg-basedir 4.0.0	xdg-basedir
	get-symbol-description 1.0.0	get-symbol-description
	unzip-response 2.0.1	unzip-response
	source-map 0.5.7	source-map
	is-extendable 0.1.1	snapdragon/node_modules/is-extendable
	is-descriptor 0.1.6	snapdragon/node_modules/is-descriptor
	ms 2.0.0	snapdragon/node_modules/ms
	define-property 0.2.5	snapdragon/node_modules/define-property
	extend-shallow 2.0.1	snapdragon/node_modules/extend-shallow
	kind-of 3.2.2	snapdragon/node_modules/is-accessor-descriptor/node_modules/kind-of
	is-accessor-descriptor 0.1.6	snapdragon/node_modules/is-accessor-descriptor
	debug 2.6.9	snapdragon/node_modules/debug
	kind-of 3.2.2	snapdragon/node_modules/is-data-descriptor/node_modules/kind-of
	is-data-descriptor 0.1.4	snapdragon/node_modules/is-data-descriptor
	kind-of 5.1.0	snapdragon/node_modules/kind-of
	snapdragon 0.8.2	snapdragon
	string.prototype.trimend 1.0.4	string.prototype.trimend
	is-plain-object 3.0.1	is-plain-object
	lodash._reinterpolate 3.0.0	lodash._reinterpolate
	pretty-ms 5.1.0	pretty-ms
	@humanwhocodes/config-array 0.5.0	@humanwhocodes/config-array
	@humanwhocodes/object-schema 1.2.0	@humanwhocodes/object-schema
	object-assign 4.1.1	object-assign
	date-time 2.1.0	date-time
	prelude-ls 1.2.1	prelude-ls
	prettier-linter-helpers 1.0.0	prettier-linter-helpers
	object-inspect 1.11.0	object-inspect
	is-stream 1.1.0	w3counter/node_modules/is-stream
	get-stream 3.0.0	w3counter/node_modules/get-stream
	prepend-http 1.0.4	w3counter/node_modules/prepend-http
	url-parse-lax 1.0.0	w3counter/node_modules/url-parse-lax
	got 6.7.1	w3counter/node_modules/got
	w3counter 3.0.1	w3counter
	path-exists 4.0.0	path-exists
	natural-compare 1.4.0	natural-compare
	wcwidth 1.0.1	wcwidth
	is-plain-object 2.0.4	is-extendable/node_modules/is-plain-object
	is-extendable 1.0.1	is-extendable
	get-stream 5.2.0	extract-zip/node_modules/get-stream
	extract-zip 2.0.1	extract-zip
	spdx-license-ids 3.0.10	spdx-license-ids
	json-parse-even-better-errors 2.3.1	json-parse-even-better-errors
	onetime 2.0.1	ora/node_modules/onetime
	restore-cursor 2.0.0	ora/node_modules/restore-cursor
	mimic-fn 1.2.0	ora/node_modules/mimic-fn
	log-symbols 2.2.0	ora/node_modules/log-symbols
	cli-cursor 2.1.0	ora/node_modules/cli-cursor
	ora 3.4.0	ora
	array-find 1.0.0	array-find
	escape-string-regexp 2.0.0	escape-string-regexp
	tar-stream 2.2.0	tar-stream
	domutils 1.4.3	domutils
	is-descriptor 1.0.2	is-descriptor
	cli-spinners 2.6.1	cli-spinners
	es-abstract 1.19.1	es-abstract
	is-negated-glob 1.0.0	is-negated-glob
	ms 2.1.3	ms
	wrappy 1.0.2	wrappy
	pupa 2.1.1	pupa
	ansi-align 3.0.1	ansi-align
	fragment-cache 0.2.1	fragment-cache
	release-zalgo 1.0.0	release-zalgo
	entities 1.1.2	entities
	is-glob 4.0.3	is-glob
	equal-length 1.0.1	equal-length
	type-fest 0.4.1	line-column-path/node_modules/type-fest
	line-column-path 2.0.0	line-column-path
	defaults 1.0.3	defaults
	source-map-url 0.4.1	source-map-url
	package-json 6.5.0	package-json
	define-property 2.0.2	define-property
	fast-levenshtein 2.0.6	fast-levenshtein
	electron-to-chromium 1.3.864	electron-to-chromium
	babel-plugin-espower 3.0.1	babel-plugin-espower
	convert-source-map 1.8.0	convert-source-map
	isobject 2.1.0	unset-value/node_modules/has-value/node_modules/isobject
	has-value 0.3.1	unset-value/node_modules/has-value
	isarray 1.0.0	unset-value/node_modules/isarray
	has-values 0.1.4	unset-value/node_modules/has-values
	unset-value 1.0.0	unset-value
	to-fast-properties 2.0.0	to-fast-properties
	decamelize-keys 1.1.0	decamelize-keys
	micromatch 4.0.4	micromatch
	is-binary-path 2.1.0	is-binary-path
	domhandler 2.3.0	domhandler
	json5 2.2.0	json5
	is-stream 2.0.1	is-stream
	webidl-conversions 3.0.1	webidl-conversions
	has-yarn 2.1.0	has-yarn
	is-ci 2.0.0	is-ci
	end-of-stream 1.4.4	end-of-stream
	globals 11.12.0	globals
	import-lazy 2.1.0	import-lazy
	espurify 2.1.1	eslint-plugin-ava/node_modules/espurify
	eslint-utils 2.1.0	eslint-plugin-ava/node_modules/eslint-utils
	eslint-visitor-keys 1.3.0	eslint-plugin-ava/node_modules/eslint-visitor-keys
	eslint-plugin-ava 11.0.0	eslint-plugin-ava
	pify 4.0.1	pify
	eslint-plugin-promise 4.3.1	eslint-plugin-promise
	reusify 1.0.4	reusify
	latest-version 5.1.0	latest-version
	defer-to-connect 1.1.3	defer-to-connect
	require-from-string 2.0.2	require-from-string
	astral-regex 2.0.0	astral-regex
	optionator 0.9.1	optionator
	xdg-basedir 3.0.0	ava/node_modules/xdg-basedir
	path-exists 3.0.0	ava/node_modules/path-exists
	pify 3.0.0	ava/node_modules/pify
	p-limit 1.3.0	ava/node_modules/p-limit
	is-obj 1.0.1	ava/node_modules/is-obj
	map-obj 2.0.0	ava/node_modules/map-obj
	global-dirs 0.1.1	ava/node_modules/global-dirs
	camelcase 4.1.0	ava/node_modules/camelcase
	p-try 1.0.0	ava/node_modules/p-try
	camelcase 5.3.1	ava/node_modules/boxen/node_modules/camelcase
	boxen 3.2.0	ava/node_modules/boxen
	ansi-regex 3.0.0	ava/node_modules/ansi-regex
	strip-ansi 4.0.0	ava/node_modules/widest-line/node_modules/strip-ansi
	string-width 2.1.1	ava/node_modules/widest-line/node_modules/string-width
	widest-line 2.0.1	ava/node_modules/widest-line
	is-installed-globally 0.1.0	ava/node_modules/is-installed-globally
	semver-diff 2.1.0	ava/node_modules/semver-diff
	ini 1.3.8	ava/node_modules/ini
	indent-string 3.2.0	ava/node_modules/redent/node_modules/indent-string
	redent 2.0.0	ava/node_modules/redent
	crypto-random-string 1.0.0	ava/node_modules/crypto-random-string
	loud-rejection 1.6.0	ava/node_modules/meow/node_modules/loud-rejection
	meow 5.0.0	ava/node_modules/meow
	update-notifier 3.0.1	ava/node_modules/update-notifier
	read-pkg 3.0.0	ava/node_modules/read-pkg
	find-up 2.1.0	ava/node_modules/read-pkg-up/node_modules/find-up
	read-pkg-up 3.0.0	ava/node_modules/read-pkg-up
	unique-string 1.0.0	ava/node_modules/unique-string
	is-npm 3.0.0	ava/node_modules/is-npm
	is-path-inside 1.0.1	ava/node_modules/is-path-inside
	type-fest 0.3.1	ava/node_modules/type-fest
	load-json-file 4.0.0	ava/node_modules/load-json-file
	emoji-regex 7.0.3	ava/node_modules/emoji-regex
	trim-newlines 2.0.0	ava/node_modules/trim-newlines
	strip-indent 2.0.0	ava/node_modules/strip-indent
	semver 5.7.1	ava/node_modules/semver
	camelcase-keys 4.2.0	ava/node_modules/camelcase-keys
	p-locate 2.0.0	ava/node_modules/p-locate
	path-type 3.0.0	ava/node_modules/path-type
	string-width 3.1.0	ava/node_modules/string-width
	locate-path 2.0.0	ava/node_modules/locate-path
	is-fullwidth-code-point 2.0.0	ava/node_modules/is-fullwidth-code-point
	dot-prop 4.2.1	ava/node_modules/configstore/node_modules/dot-prop
	write-file-atomic 2.4.3	ava/node_modules/configstore/node_modules/write-file-atomic
	make-dir 1.3.0	ava/node_modules/configstore/node_modules/make-dir
	configstore 4.0.0	ava/node_modules/configstore
	ava 2.4.0	ava
	@ava/babel-preset-transform-test-files 6.0.0	@ava/babel-preset-transform-test-files
	@ava/babel-preset-stage-4 4.0.0	@ava/babel-preset-stage-4
	@ava/babel-plugin-throws-helper 4.0.0	@ava/babel-plugin-throws-helper
	unique-temp-dir 1.0.0	unique-temp-dir
	onetime 5.1.2	onetime
	capture-stack-trace 1.0.1	capture-stack-trace
	functional-red-black-tree 1.0.1	functional-red-black-tree
	symbol-observable 1.2.0	symbol-observable
	has-flag 4.0.0	has-flag
	tr46 0.0.3	tr46
	tsutils 3.21.0	tsutils
	type-check 0.4.0	type-check
	is-windows 1.0.2	is-windows
	deep-strict-equal 0.2.0	deep-strict-equal
	lowercase-keys 2.0.0	cacheable-request/node_modules/lowercase-keys
	get-stream 5.2.0	cacheable-request/node_modules/get-stream
	cacheable-request 6.1.0	cacheable-request
	signal-exit 3.0.5	signal-exit
	is-typedarray 1.0.0	is-typedarray
	p-limit 2.3.0	p-limit
	uri-js 4.4.1	uri-js
	jsesc 0.5.0	regjsparser/node_modules/jsesc
	regjsparser 0.7.0	regjsparser
	is-obj 2.0.0	is-obj
	lowercase-keys 1.0.1	lowercase-keys
	map-obj 1.0.1	map-obj
	unicode-property-aliases-ecmascript 2.0.0	unicode-property-aliases-ecmascript
	ansi-styles 4.3.0	ansi-styles
	call-matcher 1.1.0	call-matcher
	keyv 3.1.0	keyv
	es-module-lexer 0.9.3	es-module-lexer
	filenamify-url 2.1.2	filenamify-url
	core-assert 0.2.1	core-assert
	escape-string-regexp 1.0.5	figures/node_modules/escape-string-regexp
	figures 3.2.0	figures
	subarg 1.0.0	subarg
	clean-yaml-object 0.1.0	clean-yaml-object
	mimic-fn 3.1.0	p-memoize/node_modules/mimic-fn
	p-memoize 4.0.2	p-memoize
	parse-ms 2.1.0	parse-ms
	md5-hex 3.0.1	md5-hex
	kind-of 3.2.2	snapdragon-util/node_modules/kind-of
	snapdragon-util 3.0.1	snapdragon-util
	resolve-from 4.0.0	import-fresh/node_modules/resolve-from
	import-fresh 3.3.0	import-fresh
	repeat-element 1.1.4	repeat-element
	regenerate-unicode-properties 9.0.0	regenerate-unicode-properties
	estraverse 5.2.0	esrecurse/node_modules/estraverse
	esrecurse 4.3.0	esrecurse
	global-dirs 3.0.0	global-dirs
	use 3.1.1	use
	anymatch 3.1.2	anymatch
	trim-off-newlines 1.0.2	trim-off-newlines
	string.prototype.trimstart 1.0.4	string.prototype.trimstart
	eslint-config-prettier 7.2.0	eslint-config-prettier
	is-error 2.2.2	is-error
	strip-final-newline 2.0.0	strip-final-newline
	filename-reserved-regex 2.0.0	filename-reserved-regex
	duplexer3 0.1.4	duplexer3
	type-fest 0.8.1	hasha/node_modules/type-fest
	hasha 5.2.2	hasha
	concat-map 0.0.1	concat-map
	core-js 2.6.12	core-js
	brace-expansion 1.1.11	brace-expansion
	js-types 1.0.0	js-types
	json-parse-better-errors 1.0.2	json-parse-better-errors
	repeating 2.0.1	repeating
	internal-slot 1.0.3	internal-slot
	get-set-props 0.1.0	get-set-props
	unicode-canonical-property-names-ecmascript 2.0.0	unicode-canonical-property-names-ecmascript
	lines-and-columns 1.1.6	lines-and-columns
	get-stream 6.0.1	get-stream
	watchpack 2.2.0	watchpack
	is-callable 1.2.4	is-callable
	doctrine 3.0.0	doctrine
	camelcase 2.1.1	camelcase
	fast-json-stable-stringify 2.1.0	fast-json-stable-stringify
	nth-check 1.0.2	nth-check
	isobject 3.0.1	isobject
	which 2.0.2	which
	webpack-sources 3.2.1	webpack-sources
	unc-path-regex 0.1.2	unc-path-regex
	is-retry-allowed 1.2.0	is-retry-allowed
	word-wrap 1.2.3	word-wrap
	empower-core 1.2.0	empower-core
	clone 1.0.4	clone
	open-editor 2.0.1	open-editor
	collection-visit 1.0.0	collection-visit
	es-to-primitive 1.2.1	es-to-primitive
	sudo-block 3.0.0	sudo-block
	define-properties 1.1.3	define-properties
	is-extendable 0.1.1	extglob/node_modules/is-extendable
	define-property 1.0.0	extglob/node_modules/define-property
	extend-shallow 2.0.1	extglob/node_modules/extend-shallow
	extglob 2.0.4	extglob
	normalize-url 4.5.1	normalize-url
	spdx-exceptions 2.3.0	spdx-exceptions
	buffer-from 1.1.2	buffer-from
	babel-plugin-dynamic-import-node 2.3.3	babel-plugin-dynamic-import-node
	to-regex-range 5.0.1	to-regex-range
	p-try 2.2.0	p-try
	ignore 5.1.8	ignore
	component-emitter 1.3.0	component-emitter
	@babel/generator 7.15.8	@babel/generator
	@babel/helper-validator-identifier 7.15.7	@babel/helper-validator-identifier
	@babel/helper-get-function-arity 7.15.4	@babel/helper-get-function-arity
	@babel/helper-simple-access 7.15.4	@babel/helper-simple-access
	@babel/plugin-syntax-async-generators 7.8.4	@babel/plugin-syntax-async-generators
	@babel/code-frame 7.15.8	@babel/code-frame
	@babel/plugin-syntax-optional-catch-binding 7.8.3	@babel/plugin-syntax-optional-catch-binding
	@babel/helper-annotate-as-pure 7.15.4	@babel/helper-annotate-as-pure
	@babel/parser 7.15.8	@babel/parser
	@babel/helper-wrap-function 7.15.4	@babel/helper-wrap-function
	@babel/helper-validator-option 7.14.5	@babel/helper-validator-option
	@babel/plugin-proposal-optional-catch-binding 7.14.5	@babel/plugin-proposal-optional-catch-binding
	@babel/helper-module-transforms 7.15.8	@babel/helper-module-transforms
	@babel/types 7.15.6	@babel/types
	@babel/helper-optimise-call-expression 7.15.4	@babel/helper-optimise-call-expression
	@babel/helper-remap-async-to-generator 7.15.4	@babel/helper-remap-async-to-generator
	@babel/helper-split-export-declaration 7.15.4	@babel/helper-split-export-declaration
	@babel/template 7.15.4	@babel/template
	@babel/helper-module-imports 7.15.4	@babel/helper-module-imports
	@babel/helper-compilation-targets 7.15.4	@babel/helper-compilation-targets
	@babel/plugin-transform-modules-commonjs 7.15.4	@babel/plugin-transform-modules-commonjs
	@babel/helper-member-expression-to-functions 7.15.4	@babel/helper-member-expression-to-functions
	@babel/compat-data 7.15.0	@babel/compat-data
	@babel/helper-create-regexp-features-plugin 7.14.5	@babel/helper-create-regexp-features-plugin
	@babel/traverse 7.15.4	@babel/traverse
	@babel/helper-replace-supers 7.15.4	@babel/helper-replace-supers
	@babel/plugin-transform-dotall-regex 7.14.5	@babel/plugin-transform-dotall-regex
	@babel/plugin-syntax-dynamic-import 7.8.3	@babel/plugin-syntax-dynamic-import
	@babel/helper-plugin-utils 7.14.5	@babel/helper-plugin-utils
	@babel/eslint-parser 7.15.8	@babel/eslint-parser
	@babel/core 7.15.8	@babel/core
	@babel/helper-function-name 7.15.4	@babel/helper-function-name
	@babel/highlight 7.14.5	@babel/highlight
	@babel/helper-hoist-variables 7.15.4	@babel/helper-hoist-variables
	@babel/plugin-proposal-dynamic-import 7.14.5	@babel/plugin-proposal-dynamic-import
	@babel/helpers 7.15.4	@babel/helpers
	@babel/plugin-proposal-async-generator-functions 7.15.8	@babel/plugin-proposal-async-generator-functions
	indent-string 4.0.0	indent-string
	kind-of 3.2.2	to-object-path/node_modules/kind-of
	to-object-path 0.3.0	to-object-path
	prepend-http 2.0.0	prepend-http
	timed-out 4.0.1	timed-out
	extend-shallow 3.0.2	extend-shallow
	is-arguments 1.1.1	is-arguments
	escape-string-regexp 1.0.5	trim-repeated/node_modules/escape-string-regexp
	trim-repeated 1.0.0	trim-repeated
	responselike 1.0.2	responselike
	fast-deep-equal 3.1.3	fast-deep-equal
	enquirer 2.3.6	enquirer
	fs.realpath 1.0.0	fs.realpath
	serialize-error 2.1.0	serialize-error
	resolve-url 0.2.1	resolve-url
	strip-json-comments 2.0.1	strip-json-comments
	camelcase 6.2.0	boxen/node_modules/camelcase
	chalk 4.1.2	boxen/node_modules/chalk
	type-fest 0.20.2	boxen/node_modules/type-fest
	boxen 5.1.2	boxen
	deep-is 0.1.4	deep-is
	array-includes 3.1.4	array-includes
	rimraf 3.0.2	flat-cache/node_modules/rimraf
	flat-cache 3.0.4	flat-cache
	eslint-config-xo-typescript 0.36.0	eslint-config-xo-typescript
	is-arrayish 0.2.1	is-arrayish
	copy-descriptor 0.1.1	copy-descriptor
	color-name 1.1.4	color-name
	node-fetch 2.6.5	node-fetch
	viewport-list 5.1.1	viewport-list
	capture-website 1.4.0	capture-website
	ajv 6.12.6	ajv
	decode-uri-component 0.2.0	decode-uri-component
	common-path-prefix 1.0.0	common-path-prefix
	prettier 2.4.1	prettier
	@szmarczak/http-timer 1.1.2	@szmarczak/http-timer
	is-extglob 2.1.1	is-extglob
	is-wsl 1.1.0	is-wsl
	is-root 2.1.0	is-root
	md5-o-matic 0.1.1	md5-o-matic
	is-core-module 2.7.0	is-core-module
	is-number 7.0.0	is-number
	ansi-regex 4.1.0	ansi-regex
	function-bind 1.1.1	function-bind
	irregular-plurals 2.0.0	irregular-plurals
	source-map 0.6.1	terser-webpack-plugin/node_modules/source-map
	p-limit 3.1.0	terser-webpack-plugin/node_modules/p-limit
	terser-webpack-plugin 5.2.4	terser-webpack-plugin
	arr-flatten 1.1.0	arr-flatten
	yocto-queue 0.1.0	yocto-queue
	es6-error 4.1.1	es6-error
	debug 3.2.7	eslint-import-resolver-webpack/node_modules/debug
	semver 5.7.1	eslint-import-resolver-webpack/node_modules/semver
	eslint-import-resolver-webpack 0.13.1	eslint-import-resolver-webpack
	eslint-template-visitor 2.3.2	eslint-template-visitor
	@typescript-eslint/scope-manager 4.33.0	@typescript-eslint/scope-manager
	@typescript-eslint/experimental-utils 4.33.0	@typescript-eslint/experimental-utils
	@typescript-eslint/parser 4.33.0	@typescript-eslint/parser
	semver 7.3.5	@typescript-eslint/eslint-plugin/node_modules/semver
	@typescript-eslint/eslint-plugin 4.33.0	@typescript-eslint/eslint-plugin
	@typescript-eslint/types 4.33.0	@typescript-eslint/types
	@typescript-eslint/visitor-keys 4.33.0	@typescript-eslint/visitor-keys
	globby 11.0.4	@typescript-eslint/typescript-estree/node_modules/globby
	semver 7.3.5	@typescript-eslint/typescript-estree/node_modules/semver
	@typescript-eslint/typescript-estree 4.33.0	@typescript-eslint/typescript-estree
	kind-of 5.1.0	object-copy/node_modules/is-descriptor/node_modules/kind-of
	is-descriptor 0.1.6	object-copy/node_modules/is-descriptor
	define-property 0.2.5	object-copy/node_modules/define-property
	is-accessor-descriptor 0.1.6	object-copy/node_modules/is-accessor-descriptor
	is-data-descriptor 0.1.4	object-copy/node_modules/is-data-descriptor
	kind-of 3.2.2	object-copy/node_modules/kind-of
	object-copy 0.1.0	object-copy
	at-least-node 1.0.0	at-least-node
	widest-line 3.1.0	widest-line
	source-map-resolve 0.5.3	source-map-resolve
	hosted-git-info 2.8.9	hosted-git-info
	globals 13.11.0	@eslint/eslintrc/node_modules/globals
	ignore 4.0.6	@eslint/eslintrc/node_modules/ignore
	strip-json-comments 3.1.1	@eslint/eslintrc/node_modules/strip-json-comments
	type-fest 0.20.2	@eslint/eslintrc/node_modules/type-fest
	@eslint/eslintrc 0.4.3	@eslint/eslintrc
	get-intrinsic 1.1.1	get-intrinsic
	restore-cursor 3.1.0	restore-cursor
	neo-async 2.6.2	neo-async
	glob-parent 5.1.2	glob-parent
	js-string-escape 1.0.1	js-string-escape
	fast-diff 1.2.0	fast-diff
	plur 3.1.1	plur
	call-signature 0.0.2	call-signature
	arr-union 3.1.0	arr-union
	is-path-cwd 2.2.0	is-path-cwd
	@xtuc/long 4.2.2	@xtuc/long
	@xtuc/ieee754 1.2.0	@xtuc/ieee754
	ret 0.1.15	ret
	espower-location-detector 1.0.0	espower-location-detector
	date-fns 2.25.0	date-fns
	urix 0.1.0	urix
	p-reduce 2.1.0	p-reduce
	interpret 1.4.0	interpret
	pump 3.0.0	pump
	object-keys 1.1.1	object-keys
	enhance-visitors 1.0.0	enhance-visitors
	humanize-url 2.1.1	humanize-url
	caniuse-lite 1.0.30001265	caniuse-lite
	call-bind 1.0.2	call-bind
	pseudomap 1.0.2	pseudomap
	obj-props 1.3.0	obj-props
	map-cache 0.2.2	map-cache
	modify-filename 1.1.0	modify-filename
	lodash.get 4.4.2	lodash.get
	define-property 1.0.0	snapdragon-node/node_modules/define-property
	snapdragon-node 2.1.1	snapdragon-node
	arr-diff 4.0.0	arr-diff
	run-parallel 1.2.0	run-parallel
	source-map 0.7.3	terser/node_modules/source-map
	terser 5.9.0	terser
	which-boxed-primitive 1.0.2	which-boxed-primitive
	ajv-keywords 3.5.2	ajv-keywords
	esutils 2.0.3	esutils
	jsesc 2.5.2	jsesc
	regjsgen 0.5.2	regjsgen
	fill-range 7.0.1	fill-range
	node-releases 1.1.77	node-releases
	is-path-inside 3.0.3	is-installed-globally/node_modules/is-path-inside
	is-installed-globally 0.4.0	is-installed-globally
	acorn-jsx 5.3.2	acorn-jsx
	camelcase 4.1.0	yargs-parser/node_modules/camelcase
	yargs-parser 10.1.0	yargs-parser
	escape-string-regexp 1.0.5	chalk/node_modules/escape-string-regexp
	has-flag 3.0.0	chalk/node_modules/has-flag
	ansi-styles 3.2.1	chalk/node_modules/ansi-styles
	color-name 1.1.3	chalk/node_modules/color-name
	supports-color 5.5.0	chalk/node_modules/supports-color
	color-convert 1.9.3	chalk/node_modules/color-convert
	chalk 2.4.2	chalk
	semver 5.7.1	normalize-package-data/node_modules/semver
	normalize-package-data 2.5.0	normalize-package-data
	hard-rejection 2.1.0	hard-rejection
	is-shared-array-buffer 1.0.1	is-shared-array-buffer
	eslint-utils 2.1.0	eslint-plugin-node/node_modules/eslint-utils
	eslint-visitor-keys 1.3.0	eslint-plugin-node/node_modules/eslint-visitor-keys
	eslint-plugin-node 11.1.0	eslint-plugin-node
	semver-diff 3.1.1	semver-diff
	dot-prop 5.3.0	dot-prop
	safe-regex 2.1.1	safe-regex
	is-accessor-descriptor 1.0.0	is-accessor-descriptor
	events 3.3.0	events
	parent-module 1.0.1	parent-module
	eslint-scope 5.1.1	eslint-scope
	slash 3.0.0	slash
	eslint-ast-utils 1.1.0	eslint-ast-utils
	validate-npm-package-license 3.0.4	validate-npm-package-license
	regexp-tree 0.1.24	regexp-tree
	acorn 7.4.1	acorn
	eslint-config-xo 0.33.1	eslint-config-xo
	is-number-object 1.0.6	is-number-object
	domutils 1.5.1	htmlparser2/node_modules/domutils
	entities 1.0.0	htmlparser2/node_modules/entities
	readable-stream 1.1.14	htmlparser2/node_modules/readable-stream
	string_decoder 0.10.31	htmlparser2/node_modules/string_decoder
	htmlparser2 3.8.3	htmlparser2
	readable-stream 3.6.0	readable-stream
	require-precompiled 0.1.0	require-precompiled
	schema-utils 3.1.1	schema-utils
	ws 7.5.5	ws
	js-yaml 3.14.1	js-yaml
	glob 7.2.0	glob
	regexpp 3.2.0	regexpp
	array.prototype.flat 1.2.5	array.prototype.flat
	bl 4.1.0	bl
	is-bigint 1.0.4	is-bigint
	parse-json 5.2.0	cosmiconfig/node_modules/parse-json
	cosmiconfig 7.0.1	cosmiconfig
	lodash.flattendeep 4.4.0	lodash.flattendeep
	inherits 2.0.4	inherits
	universalify 2.0.0	fs-extra/node_modules/universalify
	fs-extra 9.1.0	fs-extra
	esm 3.2.25	esm
	well-known-symbols 2.0.0	well-known-symbols
	boolbase 1.0.0	boolbase
	ini 2.0.0	ini
	find-up 4.1.0	find-up
	sprintf-js 1.0.3	sprintf-js
	xtend 4.0.2	xtend
	chunkd 1.0.0	chunkd
	is-observable 2.1.0	is-observable
	ansi-colors 4.1.1	ansi-colors
	safe-buffer 5.2.1	string_decoder/node_modules/safe-buffer
	string_decoder 1.3.0	string_decoder
	indent-string 2.1.0	redent/node_modules/indent-string
	redent 1.0.0	redent
	array-uniq 2.1.0	array-uniq
	is-symbol 1.0.4	is-symbol
	lodash.template 4.5.0	lodash.template
	map-visit 1.0.0	map-visit
	progress 2.0.3	progress
	clean-stack 2.2.0	clean-stack
	lodash 4.17.21	lodash
	minimist 1.2.5	minimist
	psl 1.8.0	psl
	crypto-random-string 2.0.0	crypto-random-string
	lodash.clonedeep 4.5.0	lodash.clonedeep
	@types/json5 0.0.29	@types/json5
	@types/estree 0.0.50	@types/estree
	@types/normalize-package-data 2.4.1	@types/normalize-package-data
	@types/eslint-scope 3.7.1	@types/eslint-scope
	@types/glob 7.1.4	@types/glob
	@types/node 16.10.3	@types/node
	@types/json-schema 7.0.9	@types/json-schema
	@types/minimist 1.2.2	@types/minimist
	@types/parse-json 4.0.0	@types/parse-json
	@types/puppeteer 5.4.4	@types/puppeteer
	@types/yauzl 2.9.2	@types/yauzl
	@types/eslint 7.28.1	@types/eslint
	@types/minimatch 3.0.5	@types/minimatch
	dir-glob 3.0.1	dir-glob
	is-utf8 0.2.1	is-utf8
	ignore-by-default 1.0.1	ignore-by-default
	get-port 5.1.1	get-port
	is-unc-path 1.0.0	is-unc-path
	p-map 2.1.0	p-map
	yallist 4.0.0	yallist
	is-boolean-object 1.1.2	is-boolean-object
	regenerate 1.4.2	regenerate
	safe-regex 1.1.0	regex-not/node_modules/safe-regex
	regex-not 1.0.2	regex-not
	time-zone 1.0.0	time-zone
	array-differ 3.0.0	array-differ
	core-util-is 1.0.3	core-util-is
	ci-parallel-vars 1.0.1	ci-parallel-vars
	supports-color 7.2.0	supports-color
	browserslist 4.17.3	browserslist
	loud-rejection 2.2.0	loud-rejection
	parse-json 4.0.0	parse-json
	ms 2.1.2	debug/node_modules/ms
	debug 4.3.2	debug
	is-url 1.2.4	is-url
	array-unique 0.3.2	array-unique
	universalify 2.0.0	jsonfile/node_modules/universalify
	jsonfile 6.1.0	jsonfile
	is-obj-prop 1.0.0	is-obj-prop
	js-tokens 4.0.0	js-tokens
	css-what 1.0.0	css-what
	pinkie-promise 2.0.1	pinkie-promise
	bluebird 3.7.2	bluebird
	domelementtype 1.3.1	domelementtype
	ini 1.3.8	rc/node_modules/ini
	rc 1.2.8	rc
	get-stdin 4.0.1	get-stdin
	arrify 2.0.1	arrify
	path-parse 1.0.7	path-parse
	get-value 2.0.6	get-value
	css-select 1.0.0	css-select
	flatted 3.2.2	flatted
	env-editor 0.4.2	env-editor
	safe-buffer 5.1.2	safe-buffer
	picomatch 2.3.0	picomatch
	escape-string-regexp 1.0.5	clean-regexp/node_modules/escape-string-regexp
	clean-regexp 1.0.0	clean-regexp
	nanomatch 1.2.13	nanomatch
	call-me-maybe 1.0.1	call-me-maybe
	is-date-object 1.0.5	is-date-object
	loud-rejection 1.6.0	meow/node_modules/loud-rejection
	meow 3.7.0	meow
	is-descriptor 0.1.6	class-utils/node_modules/is-descriptor
	define-property 0.2.5	class-utils/node_modules/define-property
	kind-of 3.2.2	class-utils/node_modules/is-accessor-descriptor/node_modules/kind-of
	is-accessor-descriptor 0.1.6	class-utils/node_modules/is-accessor-descriptor
	kind-of 3.2.2	class-utils/node_modules/is-data-descriptor/node_modules/kind-of
	is-data-descriptor 0.1.4	class-utils/node_modules/is-data-descriptor
	kind-of 5.1.0	class-utils/node_modules/kind-of
	class-utils 0.3.6	class-utils
	mkdirp 0.5.5	mkdirp
	deep-equal 1.1.1	deep-equal
	stack-utils 1.0.5	stack-utils
	lodash.islength 4.0.1	lodash.islength
	has-value 1.0.0	has-value
	trim-right 1.0.1	trim-right
	is-string 1.0.7	is-string
	spdx-expression-parse 3.0.1	spdx-expression-parse
	is-data-descriptor 1.0.0	is-data-descriptor
	pkg-dir 4.2.0	pkg-dir
	path-exists 3.0.0	pkg-conf/node_modules/path-exists
	find-up 3.0.0	pkg-conf/node_modules/find-up
	p-locate 3.0.0	pkg-conf/node_modules/p-locate
	locate-path 3.0.0	pkg-conf/node_modules/locate-path
	pkg-conf 3.1.0	pkg-conf
	registry-auth-token 4.2.1	registry-auth-token
	glob-to-regexp 0.4.1	glob-to-regexp
	balanced-match 1.0.2	balanced-match
	cache-base 1.0.1	cache-base
	array-uniq 1.0.3	del/node_modules/array-uniq
	array-union 1.0.2	del/node_modules/array-union
	pify 2.3.0	del/node_modules/globby/node_modules/pify
	globby 6.1.0	del/node_modules/globby
	del 4.1.1	del
	gensync 1.0.0-beta.2	gensync
	is-redirect 1.0.0	is-redirect
	is-descriptor 0.1.6	static-extend/node_modules/is-descriptor
	define-property 0.2.5	static-extend/node_modules/define-property
	kind-of 3.2.2	static-extend/node_modules/is-accessor-descriptor/node_modules/kind-of
	is-accessor-descriptor 0.1.6	static-extend/node_modules/is-accessor-descriptor
	kind-of 3.2.2	static-extend/node_modules/is-data-descriptor/node_modules/kind-of
	is-data-descriptor 0.1.4	static-extend/node_modules/is-data-descriptor
	kind-of 5.1.0	static-extend/node_modules/kind-of
	static-extend 0.1.2	static-extend
	escalade 3.1.1	escalade
	merge2 1.4.1	merge2
	execa 5.1.1	execa
	memory-fs 0.2.0	memory-fs
	micro-spelling-correcter 1.1.1	micro-spelling-correcter
	object.assign 4.1.2	object.assign
	rimraf 3.0.2	puppeteer/node_modules/rimraf
	puppeteer 5.5.0	puppeteer
	irregular-plurals 3.3.0	eslint-formatter-pretty/node_modules/irregular-plurals
	plur 4.0.0	eslint-formatter-pretty/node_modules/plur
	chalk 4.1.2	eslint-formatter-pretty/node_modules/chalk
	eslint-formatter-pretty 4.1.0	eslint-formatter-pretty
	yauzl 2.10.0	yauzl
	multimap 1.1.0	multimap
	pluralize 8.0.0	pluralize
	chalk 4.1.2	update-notifier/node_modules/chalk
	semver 7.3.5	update-notifier/node_modules/semver
	update-notifier 5.1.0	update-notifier
	tslib 1.14.1	tslib
	pify 2.3.0	read-pkg/node_modules/pify
	parse-json 2.2.0	read-pkg/node_modules/parse-json
	load-json-file 1.1.0	read-pkg/node_modules/load-json-file
	path-type 1.1.0	read-pkg/node_modules/path-type
	strip-bom 2.0.0	read-pkg/node_modules/strip-bom
	read-pkg 1.1.0	read-pkg
	is-extendable 0.1.1	union-value/node_modules/is-extendable
	union-value 1.0.1	union-value
	once 1.4.0	once
	error-ex 1.3.2	error-ex
	repeat-string 1.6.1	repeat-string
	estraverse 5.2.0	esquery/node_modules/estraverse
	esquery 1.4.0	esquery
	is-stream 1.1.0	term-size/node_modules/is-stream
	get-stream 3.0.0	term-size/node_modules/get-stream
	which 1.3.1	term-size/node_modules/which
	yallist 2.1.2	term-size/node_modules/yallist
	execa 0.7.0	term-size/node_modules/execa
	path-key 2.0.1	term-size/node_modules/path-key
	npm-run-path 2.0.2	term-size/node_modules/npm-run-path
	lru-cache 4.1.5	term-size/node_modules/lru-cache
	cross-spawn 5.1.0	term-size/node_modules/cross-spawn
	shebang-command 1.2.0	term-size/node_modules/shebang-command
	shebang-regex 1.0.0	term-size/node_modules/shebang-regex
	term-size 1.2.0	term-size
	acorn-import-assertions 1.8.0	webpack/node_modules/acorn-import-assertions
	acorn 8.5.0	webpack/node_modules/acorn
	enhanced-resolve 5.8.3	webpack/node_modules/enhanced-resolve
	tapable 2.2.1	webpack/node_modules/tapable
	webpack 5.58.1	webpack
	array-union 2.1.0	array-union
	ci-info 2.0.0	ci-info
	queue-microtask 1.2.3	queue-microtask
	is-path-in-cwd 2.1.0	is-path-in-cwd
	dom-serializer 0.1.1	dom-serializer
	fastq 1.13.0	fastq
	package-hash 4.0.0	package-hash
	base64-js 1.5.1	base64-js
	matcher 2.1.0	matcher
	filenamify 4.3.0	filenamify
	arrify 1.0.1	minimist-options/node_modules/arrify
	minimist-options 3.0.2	minimist-options
	is-negative-zero 2.0.1	is-negative-zero
	currently-unhandled 0.4.1	currently-unhandled
	resolve-cwd 3.0.0	resolve-cwd
	posix-character-classes 0.1.1	posix-character-classes
	object.pick 1.3.0	object.pick
	os-tmpdir 1.0.2	os-tmpdir
	lodash.templatesettings 4.2.0	lodash.templatesettings
	path-dirname 1.0.2	path-dirname
	ansi-regex 5.0.1	wrap-ansi/node_modules/ansi-regex
	strip-ansi 6.0.1	wrap-ansi/node_modules/strip-ansi
	wrap-ansi 7.0.0	wrap-ansi
	decompress-response 3.3.0	decompress-response
	path-key 3.1.1	path-key
	@webassemblyjs/wasm-opt 1.11.1	@webassemblyjs/wasm-opt
	@webassemblyjs/helper-numbers 1.11.1	@webassemblyjs/helper-numbers
	@webassemblyjs/helper-buffer 1.11.1	@webassemblyjs/helper-buffer
	@webassemblyjs/wasm-gen 1.11.1	@webassemblyjs/wasm-gen
	@webassemblyjs/floating-point-hex-parser 1.11.1	@webassemblyjs/floating-point-hex-parser
	@webassemblyjs/helper-api-error 1.11.1	@webassemblyjs/helper-api-error
	@webassemblyjs/utf8 1.11.1	@webassemblyjs/utf8
	@webassemblyjs/leb128 1.11.1	@webassemblyjs/leb128
	@webassemblyjs/helper-wasm-section 1.11.1	@webassemblyjs/helper-wasm-section
	@webassemblyjs/wasm-parser 1.11.1	@webassemblyjs/wasm-parser
	@webassemblyjs/ast 1.11.1	@webassemblyjs/ast
	@webassemblyjs/ieee754 1.11.1	@webassemblyjs/ieee754
	@webassemblyjs/wast-printer 1.11.1	@webassemblyjs/wast-printer
	@webassemblyjs/helper-wasm-bytecode 1.11.1	@webassemblyjs/helper-wasm-bytecode
	@webassemblyjs/wasm-edit 1.11.1	@webassemblyjs/wasm-edit
	mkdirp-classic 0.5.3	mkdirp-classic
	human-signals 2.1.0	human-signals
	p-finally 1.0.0	p-finally
	is-finite 1.1.0	is-finite
	side-channel 1.0.4	side-channel
	irregular-plurals 3.3.0	pageres/node_modules/irregular-plurals
	plur 4.0.0	pageres/node_modules/plur
	p-map 4.0.0	pageres/node_modules/p-map
	pageres 6.2.3	pageres
	path-is-absolute 1.0.1	path-is-absolute
	aggregate-error 3.1.0	aggregate-error
	path-exists 2.1.0	read-pkg-up/node_modules/path-exists
	find-up 1.1.2	read-pkg-up/node_modules/find-up
	read-pkg-up 1.0.1	read-pkg-up
	util-deprecate 1.0.2	util-deprecate
	argparse 1.0.10	argparse
	map-age-cleaner 0.1.3	map-age-cleaner
	espurify 1.8.1	espurify
	unbzip2-stream 1.4.3	unbzip2-stream
	pascalcase 0.1.1	pascalcase
	lodash.merge 4.6.2	lodash.merge
	callsites 3.1.0	callsites
	unique-string 2.0.0	unique-string
	is-yarn-global 0.3.0	is-yarn-global
	quick-lru 1.1.0	quick-lru
	is-weakref 1.0.1	is-weakref
	escape-string-regexp 4.0.0	eslint/node_modules/escape-string-regexp
	globals 13.11.0	eslint/node_modules/globals
	ignore 4.0.6	eslint/node_modules/ignore
	@babel/code-frame 7.12.11	eslint/node_modules/@babel/code-frame
	strip-json-comments 3.1.1	eslint/node_modules/strip-json-comments
	ansi-regex 5.0.1	eslint/node_modules/ansi-regex
	chalk 4.1.2	eslint/node_modules/chalk
	eslint-visitor-keys 1.3.0	eslint/node_modules/eslint-utils/node_modules/eslint-visitor-keys
	eslint-utils 2.1.0	eslint/node_modules/eslint-utils
	type-fest 0.20.2	eslint/node_modules/type-fest
	semver 7.3.5	eslint/node_modules/semver
	strip-ansi 6.0.1	eslint/node_modules/strip-ansi
	eslint 7.32.0	eslint
	get-res 3.0.0	get-res
	buffer 5.7.1	buffer
	is-npm 5.0.0	is-npm
	estraverse 4.3.0	estraverse
	unbox-primitive 1.0.1	unbox-primitive
	path-exists 3.0.0	eslint-plugin-import/node_modules/path-exists
	ms 2.0.0	eslint-plugin-import/node_modules/ms
	pify 3.0.0	eslint-plugin-import/node_modules/pify
	p-limit 1.3.0	eslint-plugin-import/node_modules/p-limit
	doctrine 2.1.0	eslint-plugin-import/node_modules/doctrine
	p-try 1.0.0	eslint-plugin-import/node_modules/p-try
	find-up 2.1.0	eslint-plugin-import/node_modules/find-up
	debug 2.6.9	eslint-plugin-import/node_modules/debug
	read-pkg 3.0.0	eslint-plugin-import/node_modules/read-pkg
	read-pkg-up 3.0.0	eslint-plugin-import/node_modules/read-pkg-up
	load-json-file 4.0.0	eslint-plugin-import/node_modules/load-json-file
	p-locate 2.0.0	eslint-plugin-import/node_modules/p-locate
	path-type 3.0.0	eslint-plugin-import/node_modules/path-type
	locate-path 2.0.0	eslint-plugin-import/node_modules/locate-path
	eslint-plugin-import 2.24.2	eslint-plugin-import
	is-path-inside 2.1.0	is-path-inside
	universalify 0.1.2	universalify
	merge-stream 2.0.0	merge-stream
	isarray 0.0.1	isarray
	ajv 8.6.3	table/node_modules/ajv
	ansi-regex 5.0.1	table/node_modules/ansi-regex
	slice-ansi 4.0.0	table/node_modules/slice-ansi
	strip-ansi 6.0.1	table/node_modules/strip-ansi
	json-schema-traverse 1.0.0	table/node_modules/json-schema-traverse
	table 6.7.2	table
	rimraf 2.7.1	rimraf
	array-find-index 1.0.2	array-find-index
	mime-types 2.1.33	mime-types
	@nodelib/fs.scandir 2.1.5	@nodelib/fs.scandir
	@nodelib/fs.stat 2.0.5	@nodelib/fs.stat
	@nodelib/fs.walk 1.2.8	@nodelib/fs.walk
	regexp.prototype.flags 1.3.1	regexp.prototype.flags
	spdx-correct 3.1.1	spdx-correct
	yaml 1.10.2	yaml
	is-extendable 0.1.1	expand-brackets/node_modules/is-extendable
	is-descriptor 0.1.6	expand-brackets/node_modules/is-descriptor
	ms 2.0.0	expand-brackets/node_modules/ms
	define-property 0.2.5	expand-brackets/node_modules/define-property
	extend-shallow 2.0.1	expand-brackets/node_modules/extend-shallow
	kind-of 3.2.2	expand-brackets/node_modules/is-accessor-descriptor/node_modules/kind-of
	is-accessor-descriptor 0.1.6	expand-brackets/node_modules/is-accessor-descriptor
	debug 2.6.9	expand-brackets/node_modules/debug
	kind-of 3.2.2	expand-brackets/node_modules/is-data-descriptor/node_modules/kind-of
	is-data-descriptor 0.1.4	expand-brackets/node_modules/is-data-descriptor
	kind-of 5.1.0	expand-brackets/node_modules/kind-of
	expand-brackets 2.1.4	expand-brackets
	lodash 3.10.1	cheerio/node_modules/lodash
	cheerio 0.19.0	cheerio
	fs-constants 1.0.0	fs-constants
	path-exists 3.0.0	pkg-up/node_modules/path-exists
	p-limit 1.3.0	pkg-up/node_modules/p-limit
	p-try 1.0.0	pkg-up/node_modules/p-try
	find-up 2.1.0	pkg-up/node_modules/find-up
	p-locate 2.0.0	pkg-up/node_modules/p-locate
	locate-path 2.0.0	pkg-up/node_modules/locate-path
	pkg-up 2.0.0	pkg-up
	source-map 0.6.1	source-map-support/node_modules/source-map
	source-map-support 0.5.20	source-map-support
	resolve 1.20.0	resolve
	v8-compile-cache 2.3.0	v8-compile-cache
	json5 1.0.1	tsconfig-paths/node_modules/json5
	tsconfig-paths 3.11.0	tsconfig-paths
	kind-of 3.2.2	has-values/node_modules/is-number/node_modules/kind-of
	is-number 3.0.0	has-values/node_modules/is-number
	kind-of 4.0.0	has-values/node_modules/kind-of
	has-values 1.0.0	has-values
	proto-props 2.0.0	proto-props
	braces 3.0.2	braces
	randombytes 2.1.0	randombytes
	devtools-protocol 0.0.818844	devtools-protocol
	is-relative 1.0.0	is-relative
	escape-goat 2.1.1	escape-goat
	graceful-fs 4.2.8	graceful-fs
	is-get-set-prop 1.0.0	is-get-set-prop
	http-cache-semantics 4.1.0	http-cache-semantics
	p-defer 1.0.0	p-defer
	globby 10.0.2	globby
	regexpu-core 4.8.0	regexpu-core
	mimic-fn 2.1.0	mimic-fn
	commondir 1.0.1	commondir
	escape-string-regexp 1.0.5	strip-outer/node_modules/escape-string-regexp
	strip-outer 1.0.1	strip-outer
	chalk 4.1.2	log-symbols/node_modules/chalk
	log-symbols 4.1.0	log-symbols
	eslint-utils 3.0.0	eslint-utils
	find-root 1.1.0	find-root
	proxy-from-env 1.1.0	proxy-from-env
	parse-json 5.2.0	eslint-plugin-unicorn/node_modules/parse-json
	type-fest 0.6.0	eslint-plugin-unicorn/node_modules/read-pkg/node_modules/type-fest
	read-pkg 5.2.0	eslint-plugin-unicorn/node_modules/read-pkg
	read-pkg-up 7.0.1	eslint-plugin-unicorn/node_modules/read-pkg-up
	eslint-utils 2.1.0	eslint-plugin-unicorn/node_modules/eslint-utils
	type-fest 0.8.1	eslint-plugin-unicorn/node_modules/type-fest
	eslint-visitor-keys 1.3.0	eslint-plugin-unicorn/node_modules/eslint-visitor-keys
	semver 7.3.5	eslint-plugin-unicorn/node_modules/semver
	eslint-plugin-unicorn 23.0.0	eslint-plugin-unicorn
	tar-fs 2.1.1	tar-fs
	is-absolute 1.0.0	is-absolute
	md5-hex 2.0.0	concordance/node_modules/md5-hex
	semver 5.7.1	concordance/node_modules/semver
	concordance 4.0.0	concordance
	eslint-rule-docs 1.1.231	eslint-rule-docs
	glob-to-regexp 0.3.0	@mrmlnc/readdir-enhanced/node_modules/glob-to-regexp
	@mrmlnc/readdir-enhanced 2.2.1	@mrmlnc/readdir-enhanced
	chrome-trace-event 1.0.3	chrome-trace-event
	for-in 1.0.2	for-in
	npm-run-path 4.0.1	npm-run-path
	parse-headers 2.0.4	parse-headers
	open 6.4.0	open
	lru-cache 6.0.0	lru-cache
	escape-string-regexp 1.0.5	eslint-plugin-eslint-comments/node_modules/escape-string-regexp
	eslint-plugin-eslint-comments 3.2.0	eslint-plugin-eslint-comments
	cross-spawn 7.0.3	cross-spawn
	is-docker 2.2.1	is-docker
	unicode-match-property-value-ecmascript 2.0.0	unicode-match-property-value-ecmascript
	type-fest 0.21.3	type-fest
	chownr 1.1.4	chownr
	is-extendable 0.1.1	xo/node_modules/is-extendable
	p-limit 3.1.0	xo/node_modules/p-limit
	map-obj 4.3.0	xo/node_modules/map-obj
	camelcase 5.3.1	xo/node_modules/camelcase
	to-regex-range 2.1.1	xo/node_modules/to-regex-range
	ignore 4.0.6	xo/node_modules/ignore
	kind-of 3.2.2	xo/node_modules/is-number/node_modules/kind-of
	is-number 3.0.0	xo/node_modules/is-number
	hosted-git-info 4.0.2	xo/node_modules/hosted-git-info
	is-glob 3.1.0	xo/node_modules/glob-parent/node_modules/is-glob
	glob-parent 3.1.0	xo/node_modules/glob-parent
	extend-shallow 2.0.1	xo/node_modules/fill-range/node_modules/extend-shallow
	fill-range 4.0.0	xo/node_modules/fill-range
	yargs-parser 20.2.9	xo/node_modules/yargs-parser
	normalize-package-data 3.0.3	xo/node_modules/normalize-package-data
	find-up 5.0.0	xo/node_modules/find-up
	redent 3.0.0	xo/node_modules/redent
	array-uniq 1.0.3	xo/node_modules/array-uniq
	dir-glob 2.2.2	xo/node_modules/dir-glob
	parse-json 5.2.0	xo/node_modules/parse-json
	get-stdin 8.0.0	xo/node_modules/get-stdin
	meow 8.1.2	xo/node_modules/meow
	hosted-git-info 2.8.9	xo/node_modules/read-pkg/node_modules/hosted-git-info
	normalize-package-data 2.5.0	xo/node_modules/read-pkg/node_modules/normalize-package-data
	type-fest 0.6.0	xo/node_modules/read-pkg/node_modules/type-fest
	semver 5.7.1	xo/node_modules/read-pkg/node_modules/semver
	read-pkg 5.2.0	xo/node_modules/read-pkg
	array-union 1.0.2	xo/node_modules/array-union
	arrify 1.0.1	xo/node_modules/minimist-options/node_modules/arrify
	minimist-options 4.1.0	xo/node_modules/minimist-options
	p-limit 2.3.0	xo/node_modules/read-pkg-up/node_modules/p-limit
	find-up 4.1.0	xo/node_modules/read-pkg-up/node_modules/find-up
	type-fest 0.8.1	xo/node_modules/read-pkg-up/node_modules/type-fest
	p-locate 4.1.0	xo/node_modules/read-pkg-up/node_modules/p-locate
	locate-path 5.0.0	xo/node_modules/read-pkg-up/node_modules/locate-path
	read-pkg-up 7.0.1	xo/node_modules/read-pkg-up
	quick-lru 4.0.1	xo/node_modules/quick-lru
	is-path-inside 3.0.3	xo/node_modules/is-path-inside
	@nodelib/fs.stat 1.1.3	xo/node_modules/@nodelib/fs.stat
	extend-shallow 2.0.1	xo/node_modules/braces/node_modules/extend-shallow
	braces 2.3.2	xo/node_modules/braces
	slash 2.0.0	xo/node_modules/globby/node_modules/slash
	globby 9.2.0	xo/node_modules/globby
	type-fest 0.18.1	xo/node_modules/type-fest
	micromatch 3.1.10	xo/node_modules/fast-glob/node_modules/micromatch
	fast-glob 2.2.7	xo/node_modules/fast-glob
	trim-newlines 3.0.1	xo/node_modules/trim-newlines
	strip-indent 3.0.0	xo/node_modules/strip-indent
	semver 7.3.5	xo/node_modules/semver
	camelcase-keys 6.2.2	xo/node_modules/camelcase-keys
	p-locate 5.0.0	xo/node_modules/p-locate
	pify 3.0.0	xo/node_modules/path-type/node_modules/pify
	path-type 3.0.0	xo/node_modules/path-type
	locate-path 6.0.0	xo/node_modules/locate-path
	xo 0.36.1	xo
	enhanced-resolve 0.9.1	enhanced-resolve
	url-parse-lax 3.0.0	url-parse-lax
	unicode-match-property-ecmascript 2.0.0	unicode-match-property-ecmascript
	atob 2.1.2	atob
	get-stream 4.1.0	got/node_modules/get-stream
	got 9.6.0	got
	deep-extend 0.6.0	deep-extend
	import-local 3.0.3	import-local
	lodash.zip 4.2.0	lodash.zip
	mimic-response 1.0.1	mimic-response
	object-is 1.1.5	object-is
	@sindresorhus/is 0.14.0	@sindresorhus/is
	indent-string 3.2.0	supertap/node_modules/indent-string
	ansi-regex 3.0.0	supertap/node_modules/ansi-regex
	arrify 1.0.1	supertap/node_modules/arrify
	strip-ansi 4.0.0	supertap/node_modules/strip-ansi
	supertap 1.0.0	supertap
	agent-base 5.1.1	agent-base
	normalize-path 3.0.0	normalize-path
	text-table 0.2.0	text-table
	is-proto-prop 2.0.0	is-proto-prop
	eslint-plugin-no-use-extend-native 0.5.0	eslint-plugin-no-use-extend-native
	kind-of 6.0.3	kind-of
	debug 3.2.7	eslint-import-resolver-node/node_modules/debug
	eslint-import-resolver-node 0.3.6	eslint-import-resolver-node
	typedarray-to-buffer 3.1.5	typedarray-to-buffer
	fd-slicer 1.1.0	fd-slicer
	slice-ansi 3.0.0	slice-ansi
	min-indent 1.0.1	min-indent
	eslint-utils 2.1.0	eslint-plugin-es/node_modules/eslint-utils
	eslint-visitor-keys 1.3.0	eslint-plugin-es/node_modules/eslint-visitor-keys
	eslint-plugin-es 3.0.1	eslint-plugin-es
	imurmurhash 0.1.4	imurmurhash
	shebang-command 2.0.0	shebang-command
	minimatch 3.0.4	minimatch
	resolve-from 5.0.0	resolve-from
	through 2.3.8	through
	is-regex 1.1.4	is-regex
	mixin-deep 1.3.2	mixin-deep
	find-cache-dir 3.3.2	find-cache-dir
	punycode 2.1.1	punycode
	fast-glob 3.2.7	fast-glob
	import-modules 2.1.0	import-modules
	path-exists 3.0.0	eslint-module-utils/node_modules/path-exists
	p-limit 1.3.0	eslint-module-utils/node_modules/p-limit
	p-try 1.0.0	eslint-module-utils/node_modules/p-try
	find-up 2.1.0	eslint-module-utils/node_modules/find-up
	debug 3.2.7	eslint-module-utils/node_modules/debug
	pkg-dir 2.0.0	eslint-module-utils/node_modules/pkg-dir
	p-locate 2.0.0	eslint-module-utils/node_modules/p-locate
	locate-path 2.0.0	eslint-module-utils/node_modules/locate-path
	eslint-module-utils 2.6.2	eslint-module-utils
	decamelize 1.2.0	decamelize
	emittery 0.4.1	emittery
	to-absolute-glob 2.0.2	to-absolute-glob
	reserved-words 0.1.2	reserved-words
	picocolors 0.2.1	picocolors
	is-plain-obj 1.1.0	is-plain-obj
	strip-eof 1.0.0	strip-eof
	object.values 1.1.5	object.values
	safe-regex 1.1.0	to-regex/node_modules/safe-regex
	to-regex 3.0.2	to-regex
	https-proxy-agent 4.0.0	https-proxy-agent
	registry-url 5.1.0	registry-url
	assign-symbols 1.0.0	assign-symbols
	isexe 2.0.0	isexe
	shebang-regex 3.0.0	shebang-regex
	commander 2.20.3	commander
	type-fest 0.3.1	load-json-file/node_modules/type-fest
	load-json-file 5.3.0	load-json-file
	tapable 0.1.10	tapable
	cli-boxes 2.2.1	cli-boxes
	readdirp 3.6.0	readdirp
	emoji-regex 8.0.0	emoji-regex
	esprima 4.0.1	esprima
	trim-newlines 1.0.0	trim-newlines
	typescript 4.4.3	typescript
	code-excerpt 2.1.1	code-excerpt
	convert-to-spaces 1.0.2	convert-to-spaces
	lodash.truncate 4.4.2	lodash.truncate
	supports-color 8.1.1	jest-worker/node_modules/supports-color
	jest-worker 27.2.5	jest-worker
	ieee754 1.2.1	ieee754
	unused-filename 2.1.0	unused-filename
	strip-indent 1.0.1	strip-indent
	observable-to-promise 1.0.0	observable-to-promise
	write-file-atomic 3.0.3	write-file-atomic
	ansi-escapes 4.3.2	ansi-escapes
	eslint-visitor-keys 2.1.0	eslint-visitor-keys
	cli-cursor 3.1.0	cli-cursor
	tough-cookie 4.0.0	tough-cookie
	has-symbols 1.0.2	has-symbols
	define-property 1.0.0	base/node_modules/define-property
	base 0.11.2	base
	semver 6.3.0	semver
	has 1.0.3	has
	is-promise 2.2.2	is-promise
	uid2 0.0.3	uid2
	loader-runner 4.2.0	loader-runner
	to-readable-stream 1.0.0	to-readable-stream
	confusing-browser-globals 1.0.9	confusing-browser-globals
	json-buffer 3.0.0	json-buffer
	chokidar 3.5.2	chokidar
	is-unicode-supported 0.1.0	is-unicode-supported
	file-url 3.0.0	file-url
	split-string 3.1.0	split-string
	is-buffer 1.1.6	is-buffer
	supports-hyperlinks 2.2.0	supports-hyperlinks
	strip-ansi 5.2.0	strip-ansi
	path-is-inside 1.0.2	path-is-inside
	pend 1.2.0	pend
	camelcase-keys 2.1.0	camelcase-keys
	binary-extensions 2.2.0	binary-extensions
	whatwg-url 5.0.0	whatwg-url
	buffer-crc32 0.2.13	buffer-crc32
	json-stable-stringify-without-jsonify 1.0.1	json-stable-stringify-without-jsonify
	has-tostringtag 1.0.0	has-tostringtag
	p-locate 4.1.0	p-locate
	file-entry-cache 6.0.1	file-entry-cache
	is-plain-object 2.0.4	set-value/node_modules/is-plain-object
	is-extendable 0.1.1	set-value/node_modules/is-extendable
	extend-shallow 2.0.1	set-value/node_modules/extend-shallow
	set-value 2.0.1	set-value
	buf-compare 1.0.1	buf-compare
	cli-truncate 2.1.0	cli-truncate
	create-error-class 3.0.2	create-error-class
	color-convert 2.0.1	color-convert
	path-type 4.0.0	path-type
	arrify 1.0.1	@concordance/react/node_modules/arrify
	@concordance/react 2.0.0	@concordance/react
	levn 0.4.1	levn
	json-schema-traverse 0.4.1	json-schema-traverse
	eslint-visitor-keys 1.3.0	espree/node_modules/eslint-visitor-keys
	espree 7.3.1	espree
	inflight 1.0.6	inflight
	blueimp-md5 2.19.0	blueimp-md5
	pinkie 2.0.4	pinkie
	has-bigints 1.0.1	has-bigints
	is-js-type 2.0.0	is-js-type
	eslint-plugin-prettier 3.4.1	eslint-plugin-prettier
	object-visit 1.0.1	object-visit
	p-cancelable 1.1.0	p-cancelable
	clone-response 1.0.2	clone-response
	make-dir 3.1.0	make-dir
	ansi-regex 5.0.1	string-width/node_modules/ansi-regex
	strip-ansi 6.0.1	string-width/node_modules/strip-ansi
	string-width 4.2.3	string-width
	mime-db 1.50.0	mime-db
	serialize-javascript 6.0.0	serialize-javascript
	strip-bom 3.0.0	strip-bom
	locate-path 5.0.0	locate-path
	is-fullwidth-code-point 3.0.0	is-fullwidth-code-point
	strip-bom-buf 2.0.0	strip-bom-buf
	configstore 5.0.1	configstore
"
npm2x_set_globals

# we don't have an internet connection, stop trying to download stuff >:(
export PUPPETEER_SKIP_DOWNLOAD=1
# from node_modules/puppeteer/lib/cjs/puppeteer/revisions.js
PUPPETEER_CHROMIUM_VERSION=818858

DESCRIPTION="Capture website screenshots"
HOMEPAGE="https://github.com/sindresorhus/pageres-cli"
SRC_URI="
	https://github.com/sindresorhus/pageres-cli/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz
	bundled-chromium? (
		amd64? (
			https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/${PUPPETEER_CHROMIUM_VERSION}/chrome-linux.zip -> chrome-linux-${PUPPETEER_CHROMIUM_VERSION}.zip
		)
	)
	${NPM_SRC_URI}"

LICENSE="MIT"
SLOT="0"
KEYWORDS="~amd64 ~x86"

DEPEND=""
RDEPEND="${DEPEND}
	bundled-chromium? (
		app-accessibility/at-spi2-atk
		app-crypt/libmd
		dev-libs/atk
		dev-libs/expat
		dev-libs/glib
		dev-libs/gmp
		dev-libs/libbsd
		dev-libs/libpcre
		dev-libs/libtasn1
		dev-libs/libunistring
		dev-libs/nettle
		dev-libs/nspr
		dev-libs/nss
		media-libs/alsa-lib
		media-libs/fontconfig
		media-libs/freetype
		media-libs/libpng
		media-libs/mesa
		net-dns/libidn2
		net-libs/gnutls
		net-print/cups
		sys-apps/dbus
		x11-libs/cairo
		x11-libs/gdk-pixbuf
		x11-libs/gtk+:3
		x11-libs/libX11
		x11-libs/libXau
		x11-libs/libXcomposite
		x11-libs/libXdamage
		x11-libs/libXdmcp
		x11-libs/libXext
		x11-libs/libXfixes
		x11-libs/libXrandr
		x11-libs/libXrender
		x11-libs/libdrm
		x11-libs/libxcb
		x11-libs/libxkbcommon
		x11-libs/pango
		x11-libs/pixman
	)
	!bundled-chromium? (
		www-client/chromium
	)"
BDEPEND="app-arch/unzip"

IUSE="bundled-chromium"
REQUIRED_USE="bundled-chromium? ( amd64 )"

RESTRICT="strip"

src_unpack() {
	npm2x_src_unpack

	if use bundled-chromium; then
		mkdir "${S}"/node_modules/puppeteer/.local-chromium/{,linux-${PUPPETEER_CHROMIUM_VERSION}} || die
		mv "${WORKDIR}"/chrome-linux "${S}"/node_modules/puppeteer/.local-chromium/linux-${PUPPETEER_CHROMIUM_VERSION} || die
	else
		eapply "${FILESDIR}"/Use-system-chromium.patch
	fi
}
