JDK=/opt/jetbrains-jre-bin
export CLION_JDK=${JDK}
export GOLAND_JDK=${JDK}
export IDEA_JDK=${JDK}
export PHPSTORM_JDK=${JDK}
export PYCHARM_JDK=${JDK}
export RIDER_JDK=${JDK}
export RUBYMINE_JDK=${JDK}
export STUDIO_JDK=${JDK}
export WEBIDE_JDK=${JDK}
