JDK=/opt/jetbrains-jre-bin
export CLION_JDK=${IDEA_JDK=${JDK}}
export GOLAND_JDK=${GOLAND_JDK=${JDK}}
export IDEA_JDK=${IDEA_JDK=${JDK}}
export PHPSTORM_JDK=${PHPSTORM_JDK=${JDK}}
export PYCHARM_JDK=${PYCHARM_JDK=${JDK}}
export RIDER_JDK=${RIDER_JDK=${JDK}}
export RUBYMINE_JDK=${RUBYMINE_JDK=${JDK}}
export STUDIO_JDK=${STUDIO_JDK=${JDK}}
export WEBIDE_JDK=${WEBIDE_JDK=${JDK}}
